
include: "rules/common.smk"
include: "rules/ascp_forward_md5.smk"
include: "rules/ascp_reverse_md5.smk"
include: "rules/ascp_forward.smk"
include: "rules/ascp_reverse.smk"
include: "rules/md5dum_check_forward.smk"
include: "rules/md5dum_check_reverse.smk"
include: "rules/fastp.smk"
include: "rules/gunzip_reference.smk"
include: "rules/samtools_faidx.smk"
include: "rules/make_window_fasta.smk"
include: "rules/gunzip_reference_window.smk"
include: "rules/samtools_faidx_window.smk"
include: "rules/bwa_index.smk"
include: "rules/bwa_mem.smk"
include: "rules/samtools_view.smk"
include: "rules/samtools_sort.smk"
include: "rules/picard_markduplicates.smk"
include: "rules/bcftools_mpileup.smk"
include: "rules/bcftools_call.smk"

rule all:
    input:
        "bcftools/calls.bcf"
              
